# Generated by Django 4.2.11 on 2024-03-07 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='user',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
