# Generated by Django 4.2.11 on 2024-03-07 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_alter_category_user_remove_price_thing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='user',
        ),
        migrations.RemoveField(
            model_name='thing',
            name='user',
        ),
    ]
