# Generated by Django 4.2.11 on 2024-03-07 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0004_remove_price_user_remove_thing_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='thing',
        ),
        migrations.RemoveField(
            model_name='thing',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.DeleteModel(
            name='Thing',
        ),
    ]
