# Generated by Django 4.2.11 on 2024-03-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0008_thing_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='date',
            field=models.CharField(max_length=20),
        ),
    ]
