# Generated by Django 4.2.11 on 2024-03-16 08:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial', '0009_alter_price_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Price',
            new_name='Cost',
        ),
    ]
